### ISSUE TITLE
Project doesn't run

### ISSUE THREAD

**Issue by forresthopkinsa** [DMBuce/norbert#1]
There are a few issues that stop this project from being able to run, but the one that I can't work around is that `exceptions.py` seems to be uncommitted

**Comment by forresthopkinsa** [comment]
Thanks!

**Comment by DMBuce** [comment]
Sure thing. Note that I haven't touched this project in years and it might not work. If master gives you trouble I would recommend giving the most recent tag a try.

P.S. if you're just looking for a command line NBT editor, I'd recommend nbted. I switched to it a while ago and it's always been solid.

https://github.com/C4K3/nbted

**Comment by forresthopkinsa** [comment]
Gotcha, sounds good!
